import { ConnectButton } from "@rainbow-me/rainbowkit";
import { Flex, Text } from "@chakra-ui/react";
import Link from "next/link";
import Head from "next/head";
import NavLink from "@/components/NavLink";

export const Header = () => {
  return (
    <>
      <Head>
        <title>Voting</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex
        bg="gray"
        h="15vh"
        p="2rem"
        justifyContent="space-between"
        alignItems="center"
      >
        <NavLink to="/">Voting</NavLink>
        <Flex
          direction={{ base: "column", xl: "row" }}
          justifyContent="space-between"
          alignItems="center"
          width="25%"
        >
          <NavLink to="/add-voter">Add Voter</NavLink>
          <NavLink to="/proposals">Proposals</NavLink>
        </Flex>
        <ConnectButton />
      </Flex>
    </>
  );
};
